# generated by datamodel-codegen from UNTP v0.7.0 DigitalIdentityAnchor.json
# (bundled copy under untp/bundled/; JSON `prefixItems` stripped for codegen — see scripts/generate_untp_pydantic_models.py)

from __future__ import annotations

from datetime import date
from enum import StrEnum

from pydantic import AnyUrl, AwareDatetime, BaseModel, ConfigDict, Field


class Type(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True,
    )


class IssuerAlsoKnownA(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    id: AnyUrl = Field(
        ...,
        description="Globally unique identifier of this party. Typically represented as a URI identifierScheme/Identifier URI",
        examples=["https://sample-business-register.gov/123456789"],
    )
    name: str = Field(
        ...,
        description="Legal registered name of this party.",
        examples=["Sample Company Ltd"],
    )
    registeredId: str | None = Field(
        default=None,
        description="The registration number (alphanumeric) of the Party within the register. Unique within the register.",
        examples=[90664869327],
    )


class CredentialIssuer(BaseModel):
    """
    The issuer party (person or organisation) of a verifiable credential.
    """

    model_config = ConfigDict(
        extra="forbid",
        populate_by_name=True,
    )
    type: list[str] | Type | None = Field(
        default_factory=lambda: Type.model_validate(["CredentialIssuer"])
    )
    id: AnyUrl = Field(
        ...,
        description="The W3C DID of the issuer - should be a did:web or did:webvh",
        examples=["did:web:identifiers.example-company.com:12345"],
    )
    name: str = Field(
        ...,
        description="The name of the issuer person or organisation",
        examples=["Example Company Pty Ltd"],
    )
    issuerAlsoKnownAs: list[IssuerAlsoKnownA] | None = Field(
        default=None,
        description="An optional list of other registered identifiers for this credential issuer ",
    )


class Type2(StrEnum):
    """
    The type of status list - must be set to "The type property MUST be BitstringStatusListEntry."
    """

    BitstringStatusListEntry = "BitstringStatusListEntry"


class StatusPurpose(StrEnum):
    """
    Status purpose drawn from a standard list but extensible as per w3c bitstring status list specification.
    """

    refresh = "refresh"
    revocation = "revocation"
    suspension = "suspension"
    message = "message"


class BitstringStatusListEntry(BaseModel):
    """
    A privacy-preserving, space-efficient, and high-performance mechanism for publishing status information such as suspension or revocation of Verifiable Credentials through use of bitstrings.  See https://www.w3.org/TR/vc-bitstring-status-list/ for full details.
    """

    model_config = ConfigDict(
        extra="forbid",
        populate_by_name=True,
    )
    type: Type2 = Field(
        ...,
        description='The type of status list - must be set to "The type property MUST be BitstringStatusListEntry."',
        examples=["BitstringStatusListEntry"],
    )
    id: AnyUrl | None = Field(
        default=None,
        description="optional identifer of this status list entry.",
        examples=['https://example-cab.com/credentials/status/3#94567"'],
    )
    statusPurpose: StatusPurpose = Field(
        ...,
        description="Status purpose drawn from a standard list but extensible as per w3c bitstring status list specification.",
        examples=["refresh"],
    )
    statusListIndex: int = Field(
        ...,
        description="\tThe statusListIndex property MUST be an arbitrary size integer greater than or equal to 0, expressed as a string in base 10. The value identifies the position of the status of the verifiable credential.",
        examples=[94567],
        ge=0,
    )
    statusListCredential: AnyUrl = Field(
        ...,
        description="The statusListCredential property MUST be a URL to a verifiable credential. When the URL is dereferenced, the resulting verifiable credential MUST have type property that includes the BitstringStatusListCredential value.",
        examples=["https://example-cab.com/credentials/status/4"],
    )


class Type3(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True,
    )


class RenderTemplate2024(BaseModel):
    """
    A single template format focused render method where the content/media type decision becomes secondary (and is expressed separately).See https://github.com/w3c-ccg/vc-render-method/issues/9
    """

    model_config = ConfigDict(
        extra="forbid",
        populate_by_name=True,
    )
    type: list[str] | Type3 | None = Field(
        default_factory=lambda: Type3.model_validate(["RenderTemplate2024"])
    )
    name: str | None = Field(
        default=None, description="Human facing display name for selection"
    )
    mediaQuery: str | None = Field(
        default=None,
        description="Media query as defined in https://www.w3.org/TR/mediaqueries-4/",
    )
    template: str | None = Field(
        default=None,
        description="An inline template field for use cases where remote retrieval of a render method is suboptimal",
    )
    url: AnyUrl | None = Field(
        default=None, description="URL for remotely hosted template"
    )
    mediaType: str | None = Field(
        default=None, description="media type of the rendered output (eg text/html)"
    )
    digestMultibase: str | None = Field(
        default=None,
        description="Used for resource integrity and/or validation of the inline `template`",
    )


class Registrar(BaseModel):
    """
    The registrar party that operates the register.
    """

    model_config = ConfigDict(
        populate_by_name=True,
    )
    id: AnyUrl = Field(
        ...,
        description="Globally unique identifier of this party. Typically represented as a URI identifierScheme/Identifier URI",
        examples=["https://sample-business-register.gov/123456789"],
    )
    name: str = Field(
        ...,
        description="Legal registered name of this party.",
        examples=["Sample Company Ltd"],
    )


class RegisterType(StrEnum):
    """
    The thematic purpose of the register - organisations, facilities, products, trademarks, etc
    """

    product = "product"
    facility = "facility"
    business = "business"
    trademark = "trademark"
    land = "land"
    accreditation = "accreditation"


class IdentifierScheme(BaseModel):
    """
    An identifier registration scheme for products, facilities, or organisations. Typically operated by a state, national or global authority.
    """

    model_config = ConfigDict(
        extra="forbid",
        populate_by_name=True,
    )
    type: list[str] | Type3 | None = Field(
        default_factory=lambda: Type3.model_validate(["IdentifierScheme"])
    )
    id: AnyUrl = Field(..., description="The URI of this identifier scheme")
    name: str = Field(
        ...,
        description="The name of the identifier scheme. ",
        examples=["Global Identifier Scheme Name"],
    )


class RegisteredIdentity(BaseModel):
    """
    The identity anchor is a mapping between a registry member identity and one or more decentralised identifiers owned by the member. It may also list a set of membership scopes.
    """

    model_config = ConfigDict(
        extra="allow",
        populate_by_name=True,
    )
    type: list[str] | Type3 | None = Field(
        default_factory=lambda: Type3.model_validate(["RegisteredIdentity"])
    )
    id: AnyUrl = Field(
        ...,
        description="The DID that is controlled by the registered member and is linked to the registeredID through this Identity Anchor credential",
        examples=["did:web:samplecompany.com/123456789"],
    )
    registeredName: str = Field(
        ...,
        description="The registered name of the entity within the identifier scheme.  Examples: product - EV battery 300Ah, Party - Sample Company Pty Ltd,  Facility - Green Acres battery factory ",
        examples=["Sample business Ltd"],
    )
    registeredId: str = Field(
        ...,
        description="The registration number (alphanumeric) of the entity within the register. Unique within the register.",
        examples=[123456789],
    )
    registeredDate: date = Field(
        ...,
        description="The date on which this identity was first registered with the registrar.",
    )
    publicInformation: AnyUrl | None = Field(
        default=None,
        description="A link to further information about the registered entity on the authoritative registrar site.",
    )
    schemeId: IdentifierScheme = Field(
        ..., description="The identifier scheme operated by the registrar"
    )
    registrar: Registrar | None = Field(
        default=None, description="The registrar party that operates the register."
    )
    registerType: RegisterType = Field(
        ...,
        description="The thematic purpose of the register - organisations, facilities, products, trademarks, etc",
        examples=["product"],
    )
    registrationScope: list[AnyUrl] | None = Field(
        default=None,
        description='List of URIs that represent the roles or scopes of membership. For example ["https://abr.business.gov.au/Help/EntityTypeDescription?Id=19"]',
    )


class DigitalIdentityAnchor(BaseModel):
    """
    The Digital Identity Anchor (DIA) is a very simple credential that is issued by a trusted authority and asserts an equivalence between a member identity as known to the authority (eg a VAT number) and one or more decentralised identifiers (DIDs) held by the member.
    """

    model_config = ConfigDict(
        extra="allow",
        populate_by_name=True,
    )
    type: list[str] | Type | None = Field(
        default_factory=lambda: Type.model_validate(
            ["DigitalIdentityAnchor", "VerifiableCredential"]
        )
    )
    field_context: list[str] | None = Field(
        default=[
            "https://www.w3.org/ns/credentials/v2",
            "https://vocabulary.uncefact.org/untp/0.7.0/context/",
        ],
        alias="@context",
        description="A list of JSON-LD context URIs that define the semantic meaning of properties within the credential. ",
        examples=[
            [
                "https://www.w3.org/ns/credentials/v2",
                "https://vocabulary.uncefact.org/untp/0.7.0/context/",
            ]
        ],
        min_length=2,
    )
    id: AnyUrl = Field(
        ...,
        description="A unique identifier (URI) assigned to this verifiable credential.",
        examples=[
            "https://example-company.com/credentials/2a423366-a0d6-4855-ba65-2e0c926d09b0"
        ],
    )
    issuer: CredentialIssuer = Field(
        ...,
        description='The organisation that is the issuer of this VC. Note that the "id" property MUST be a W3C DID.  Other identifiers such as tax registration numbers can be listed in the "otherIdentifiers" property.',
    )
    validFrom: AwareDatetime = Field(
        ...,
        description="The date and time from which the credential is valid.",
        examples=["2024-03-15T12:00:00Z"],
    )
    validUntil: AwareDatetime | None = Field(
        default=None,
        description="The expiry date (if applicable) of this verifiable credential.",
        examples=["2034-03-15T12:00:00Z"],
    )
    name: str = Field(
        ...,
        description="Name of this verifiable credential instance (eg the title of a digital product passport, facility record, lifecycle event, or conformity credential)",
        examples=["Some name"],
    )
    credentialStatus: BitstringStatusListEntry | None = Field(
        default=None,
        description="A W3C VCDM2.0 compliant object containing credential status information.",
    )
    renderTemplate2024: RenderTemplate2024 | None = Field(
        default=None, description="Human rendering information for this credential."
    )
    credentialSubject: RegisteredIdentity = Field(
        ...,
        description="The registered identity from the authoritative register that is the subject of this credential",
    )
