# generated by datamodel-codegen from UNTP v0.7.0 RegisteredIdentity.json
# (bundled copy under untp/bundled/; JSON `prefixItems` stripped for codegen — see scripts/generate_untp_pydantic_models.py)

from __future__ import annotations

from datetime import date
from enum import StrEnum

from pydantic import AnyUrl, BaseModel, ConfigDict, Field


class Type(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True,
    )


class Registrar(BaseModel):
    """
    The registrar party that operates the register.
    """

    model_config = ConfigDict(
        populate_by_name=True,
    )
    id: AnyUrl = Field(
        ...,
        description="Globally unique identifier of this party. Typically represented as a URI identifierScheme/Identifier URI",
        examples=["https://sample-business-register.gov/123456789"],
    )
    name: str = Field(
        ...,
        description="Legal registered name of this party.",
        examples=["Sample Company Ltd"],
    )


class RegisterType(StrEnum):
    """
    The thematic purpose of the register - organisations, facilities, products, trademarks, etc
    """

    product = "product"
    facility = "facility"
    business = "business"
    trademark = "trademark"
    land = "land"
    accreditation = "accreditation"


class IdentifierScheme(BaseModel):
    """
    An identifier registration scheme for products, facilities, or organisations. Typically operated by a state, national or global authority.
    """

    model_config = ConfigDict(
        extra="forbid",
        populate_by_name=True,
    )
    type: list[str] | Type | None = Field(
        default_factory=lambda: Type.model_validate(["IdentifierScheme"])
    )
    id: AnyUrl = Field(..., description="The URI of this identifier scheme")
    name: str = Field(
        ...,
        description="The name of the identifier scheme. ",
        examples=["Global Identifier Scheme Name"],
    )


class RegisteredIdentity(BaseModel):
    """
    The identity anchor is a mapping between a registry member identity and one or more decentralised identifiers owned by the member. It may also list a set of membership scopes.
    """

    model_config = ConfigDict(
        extra="allow",
        populate_by_name=True,
    )
    type: list[str] | Type | None = Field(
        default_factory=lambda: Type.model_validate(["RegisteredIdentity"])
    )
    id: AnyUrl = Field(
        ...,
        description="The DID that is controlled by the registered member and is linked to the registeredID through this Identity Anchor credential",
        examples=["did:web:samplecompany.com/123456789"],
    )
    registeredName: str = Field(
        ...,
        description="The registered name of the entity within the identifier scheme.  Examples: product - EV battery 300Ah, Party - Sample Company Pty Ltd,  Facility - Green Acres battery factory ",
        examples=["Sample business Ltd"],
    )
    registeredId: str = Field(
        ...,
        description="The registration number (alphanumeric) of the entity within the register. Unique within the register.",
        examples=[123456789],
    )
    registeredDate: date = Field(
        ...,
        description="The date on which this identity was first registered with the registrar.",
    )
    publicInformation: AnyUrl | None = Field(
        default=None,
        description="A link to further information about the registered entity on the authoritative registrar site.",
    )
    schemeId: IdentifierScheme = Field(
        ..., description="The identifier scheme operated by the registrar"
    )
    registrar: Registrar | None = Field(
        default=None, description="The registrar party that operates the register."
    )
    registerType: RegisterType = Field(
        ...,
        description="The thematic purpose of the register - organisations, facilities, products, trademarks, etc",
        examples=["product"],
    )
    registrationScope: list[AnyUrl] | None = Field(
        default=None,
        description='List of URIs that represent the roles or scopes of membership. For example ["https://abr.business.gov.au/Help/EntityTypeDescription?Id=19"]',
    )
